config/routes.rb
Rails.application.routes.draw do
  
  resources :items

  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def new
	end

	def create
		@item = Item.new(item_params)

		@item.save
		redirect_to @item
	end

	def show
		@item = Item.find(params[:id])
	end

	private
		def item_params
			params.require(:item).permit(:title, :start_price, :bit_price)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@items = Item.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/new.html.erb
<h1>List Item</h1>


<%= form_for :item, url: items_path do |f| %>
	<p>
		<%= f.label :title %>
		<br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :start_price %>
		<br>
		<%= f.number_field :start_price %>
	</p>

	<p>
		<%= f.label "'Buy it now' Price" %>
		<br>
		<%= f.number_field :bit_price %>
	</p>

	<p>
		<%= f.label :end_date %>
		<br>
		<%= f.datetime_select :end_date %>
	</p>

	<p>
		<%= f.submit %>
	</p>
	
<% end %>

app/views/items/show.html.erb
<h1> Item show </h1>

<p> 
	<%= @item.title %>
	<%= @item.start_price %>
	<%= @item.bit_price %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnackList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'List Item', new_item_path %>

<table>
	<tr>
		<th>Title</th>
		<th> </th>
	</tr>

	<% @items.each do |item| %>
		<tr>
			<td><%= item.title%> </td>
			<td><%= link_to 'Show', item_path(item) %> </td>
		</tr>
	<% end %>
</table>